version: '3.8'

services:
  catalog-service:
    build: ./src/catalog-service
    ports:
      - "3001:3000"

  client-service:
    build: ./src/client-service
    ports:
      - "8080:80"

  order-service:
    build: ./src/order-service
    ports:
      - "3002:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
