version: '3.8'

services:
  catalog-server:
    image: catalog-service
    build:
      context: .
      target: catalog-service-production
    volumes:
      - catalog-db:/app/src/catalog-service
      - ./src/nginx:/app/src/nginx:ro
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  order-server:
    image: order-service
    build:
      context: .
      target: order-service-production
    volumes:
      - ./src/order-service:/app/src/order-service:ro
      - ./src/nginx:/app/src/nginx:ro
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  client:
    image: client-service
    build:
      context: .
      target: client-service-production
    volumes:
      - ./src/client-service:/app/src/client-service:ro
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8083:80'
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - catalog-server
      - order-server
      - client

  redis:
    image: redis

volumes:
  catalog-db: